-- MySQL Script generated by MySQL Workbench
-- Tue Sep 22 08:12:35 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nextage
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nextage` ;

-- -----------------------------------------------------
-- Schema nextage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nextage` DEFAULT CHARACTER SET utf8mb4 ;
USE `nextage` ;

-- -----------------------------------------------------
-- Table `nextage`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`disciplinas` (
  `id_disciplina` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_disciplina`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nextage`.`conteudos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`conteudos` (
  `id_conteudo` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_conteudo`),
  INDEX `id_disciplina` (`id_disciplina` ASC) VISIBLE,
  CONSTRAINT `conteudos_ibfk_1`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `nextage`.`disciplinas` (`id_disciplina`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nextage`.`usuarios_administradores_estudantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`usuarios_administradores_estudantes` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(1000) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nextage`.`materiais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`materiais` (
  `id_material` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `titulo` VARCHAR(200) NOT NULL,
  `material_arquivo` VARCHAR(255) NULL,
  `data_publicacao` DATE NOT NULL,
  `autor` VARCHAR(300) NOT NULL,
  `aprovado_publicacao` TINYINT(1) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_material`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `materiais_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `nextage`.`usuarios_administradores_estudantes` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nextage`.`conteudo_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`conteudo_material` (
  `id_conteudo` INT NOT NULL,
  `id_material` INT NOT NULL,
  PRIMARY KEY (`id_conteudo`, `id_material`),
  INDEX `id_material` (`id_material` ASC) VISIBLE,
  CONSTRAINT `conteudo_material_ibfk_1`
    FOREIGN KEY (`id_conteudo`)
    REFERENCES `nextage`.`conteudos` (`id_conteudo`),
  CONSTRAINT `conteudo_material_ibfk_2`
    FOREIGN KEY (`id_material`)
    REFERENCES `nextage`.`materiais` (`id_material`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nextage`.`topicos_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`topicos_forum` (
  `id_topico` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `titulo` VARCHAR(200) NOT NULL,
  `descricao` VARCHAR(2000) NOT NULL,
  `data_publicacao` DATE NOT NULL,
  PRIMARY KEY (`id_topico`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `topicos_forum_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `nextage`.`usuarios_administradores_estudantes` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nextage`.`conteudos_topicosforum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`conteudos_topicosforum` (
  `id_topico` INT NOT NULL,
  `id_conteudo` INT NOT NULL,
  PRIMARY KEY (`id_topico`, `id_conteudo`),
  INDEX `id_conteudo` (`id_conteudo` ASC) VISIBLE,
  CONSTRAINT `conteudos_topicosforum_ibfk_1`
    FOREIGN KEY (`id_topico`)
    REFERENCES `nextage`.`topicos_forum` (`id_topico`),
  CONSTRAINT `conteudos_topicosforum_ibfk_2`
    FOREIGN KEY (`id_conteudo`)
    REFERENCES `nextage`.`conteudos` (`id_conteudo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nextage`.`cronograma_estudos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`cronograma_estudos` (
  `id_cronograma` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `domingo` VARCHAR(1000) NOT NULL,
  `segunda` VARCHAR(1000) NOT NULL,
  `terca` VARCHAR(1000) NOT NULL,
  `quarta` VARCHAR(1000) NOT NULL,
  `quinta` VARCHAR(1000) NOT NULL,
  `sexta` VARCHAR(1000) NOT NULL,
  `sabado` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id_cronograma`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `cronograma_estudos_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `nextage`.`usuarios_administradores_estudantes` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nextage`.`cronometros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`cronometros` (
  `id_cronometro` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `data` DATE NOT NULL,
  `tempo_estudado` TIME NOT NULL,
  PRIMARY KEY (`id_cronometro`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `cronometros_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `nextage`.`usuarios_administradores_estudantes` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nextage`.`vestibulares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`vestibulares` (
  `id_vestibular` INT NOT NULL AUTO_INCREMENT,
  `edicao` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `banca` VARCHAR(255) NOT NULL,
  `ano` YEAR NOT NULL,
  PRIMARY KEY (`id_vestibular`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nextage`.`questoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`questoes` (
  `id_questao` INT NOT NULL AUTO_INCREMENT,
  `id_vestibular` INT NOT NULL,
  `id_alternativa_correta` INT NOT NULL,
  `explicacao` TEXT NULL,
  `enunciado` TEXT NOT NULL,
  `imagem` MEDIUMBLOB NULL,
  PRIMARY KEY (`id_questao`),
  INDEX `id_vestibular` (`id_vestibular` ASC) VISIBLE,
  CONSTRAINT `questoes_ibfk_1`
    FOREIGN KEY (`id_vestibular`)
    REFERENCES `nextage`.`vestibulares` (`id_vestibular`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nextage`.`questoes_conteudos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`questoes_conteudos` (
  `id_questao` INT NOT NULL,
  `id_conteudo` INT NOT NULL,
  PRIMARY KEY (`id_questao`, `id_conteudo`),
  INDEX `id_conteudo` (`id_conteudo` ASC) VISIBLE,
  CONSTRAINT `questoes_conteudos_ibfk_1`
    FOREIGN KEY (`id_questao`)
    REFERENCES `nextage`.`questoes` (`id_questao`),
  CONSTRAINT `questoes_conteudos_ibfk_2`
    FOREIGN KEY (`id_conteudo`)
    REFERENCES `nextage`.`conteudos` (`id_conteudo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nextage`.`relatorio_desempenho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`relatorio_desempenho` (
  `id_relatorio` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `horas_estudadas` TIME NOT NULL,
  `total_erros` INT NOT NULL,
  `total_acertos` INT NOT NULL,
  PRIMARY KEY (`id_relatorio`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `relatorio_desempenho_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `nextage`.`usuarios_administradores_estudantes` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nextage`.`responder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`responder` (
  `id_usuario` INT NOT NULL,
  `id_questao` INT NOT NULL,
  `data` DATE NOT NULL,
  `certo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_questao`),
  INDEX `id_questao` (`id_questao` ASC) VISIBLE,
  CONSTRAINT `responder_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `nextage`.`usuarios_administradores_estudantes` (`id_usuario`),
  CONSTRAINT `responder_ibfk_2`
    FOREIGN KEY (`id_questao`)
    REFERENCES `nextage`.`questoes` (`id_questao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nextage`.`alternativas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nextage`.`alternativas` (
  `id_alternativas` INT NOT NULL AUTO_INCREMENT,
  `questoes_id_questao` INT NOT NULL,
  `texto` VARCHAR(255) NULL,
  PRIMARY KEY (`id_alternativas`),
  INDEX `fk_alternativas_questoes1_idx` (`questoes_id_questao` ASC) VISIBLE,
  CONSTRAINT `fk_alternativas_questoes1`
    FOREIGN KEY (`questoes_id_questao`)
    REFERENCES `nextage`.`questoes` (`id_questao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `nextage`.`disciplinas`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`disciplinas` (`id_disciplina`, `nome`) VALUES (1, 'Matemática');
INSERT INTO `nextage`.`disciplinas` (`id_disciplina`, `nome`) VALUES (2, 'Português');
INSERT INTO `nextage`.`disciplinas` (`id_disciplina`, `nome`) VALUES (3, 'Biologia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `nextage`.`conteudos`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`conteudos` (`id_conteudo`, `id_disciplina`, `nome`) VALUES (1, 1, 'Funções');
INSERT INTO `nextage`.`conteudos` (`id_conteudo`, `id_disciplina`, `nome`) VALUES (2, 2, 'Interpretação de Texto');
INSERT INTO `nextage`.`conteudos` (`id_conteudo`, `id_disciplina`, `nome`) VALUES (3, 3, 'Genética');

COMMIT;


-- -----------------------------------------------------
-- Data for table `nextage`.`usuarios_administradores_estudantes`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`usuarios_administradores_estudantes` (`id_usuario`, `nome`, `email`, `senha`, `data_nascimento`, `tipo_usuario`) VALUES (1, 'João Silva', 'joao@email.com', '123456', '2010-12-12', 0);
INSERT INTO `nextage`.`usuarios_administradores_estudantes` (`id_usuario`, `nome`, `email`, `senha`, `data_nascimento`, `tipo_usuario`) VALUES (2, 'Maria Souza', 'maria@email.com', '654321', '2010-12-12', 0);
INSERT INTO `nextage`.`usuarios_administradores_estudantes` (`id_usuario`, `nome`, `email`, `senha`, `data_nascimento`, `tipo_usuario`) VALUES (3, 'Carlos Lima', 'carlos@email.com', 'abcdef', '2010-12-12', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `nextage`.`materiais`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`materiais` (`id_material`, `id_usuario`, `titulo`, `material_arquivo`, `data_publicacao`, `autor`, `aprovado_publicacao`, `descricao`) VALUES (1, 1, 'Resumo de Funções', NULL, '2025-05-05', 'João Silva', TRUE, 'Resumo completo');
INSERT INTO `nextage`.`materiais` (`id_material`, `id_usuario`, `titulo`, `material_arquivo`, `data_publicacao`, `autor`, `aprovado_publicacao`, `descricao`) VALUES (2, 2, 'Gramática Básica', NULL, '2025-05-06', 'Maria Souza', TRUE, 'Material sobre gramática.');
INSERT INTO `nextage`.`materiais` (`id_material`, `id_usuario`, `titulo`, `material_arquivo`, `data_publicacao`, `autor`, `aprovado_publicacao`, `descricao`) VALUES (3, 3, 'Mapa Mental Genética', NULL, '2025-05-07', 'Carlos Lima', FALSE, 'Mapa mental para revisão.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `nextage`.`conteudo_material`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`conteudo_material` (`id_conteudo`, `id_material`) VALUES (1, 1);
INSERT INTO `nextage`.`conteudo_material` (`id_conteudo`, `id_material`) VALUES (2, 2);
INSERT INTO `nextage`.`conteudo_material` (`id_conteudo`, `id_material`) VALUES (3, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `nextage`.`topicos_forum`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`topicos_forum` (`id_topico`, `id_usuario`, `titulo`, `descricao`, `data_publicacao`) VALUES (1, 1, 'Dúvida sobre funções', 'Como resolver funções do 1º grau?', '2025-05-01');
INSERT INTO `nextage`.`topicos_forum` (`id_topico`, `id_usuario`, `titulo`, `descricao`, `data_publicacao`) VALUES (2, 2, 'Gramática Básica', 'Material sobre gramática.', '2025-05-02');
INSERT INTO `nextage`.`topicos_forum` (`id_topico`, `id_usuario`, `titulo`, `descricao`, `data_publicacao`) VALUES (3, 3, 'Mapa Mental Genética', 'Mapa Mental Genética', '2025-05-03');

COMMIT;


-- -----------------------------------------------------
-- Data for table `nextage`.`conteudos_topicosforum`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`conteudos_topicosforum` (`id_topico`, `id_conteudo`) VALUES (1, 1);
INSERT INTO `nextage`.`conteudos_topicosforum` (`id_topico`, `id_conteudo`) VALUES (2, 2);
INSERT INTO `nextage`.`conteudos_topicosforum` (`id_topico`, `id_conteudo`) VALUES (3, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `nextage`.`cronograma_estudos`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`cronograma_estudos` (`id_cronograma`, `id_usuario`, `domingo`, `segunda`, `terca`, `quarta`, `quinta`, `sexta`, `sabado`) VALUES (1, 1, 'Descanso', 'Matemática', 'Português', 'Biologia', 'História', 'Química', 'Revisão');
INSERT INTO `nextage`.`cronograma_estudos` (`id_cronograma`, `id_usuario`, `domingo`, `segunda`, `terca`, `quarta`, `quinta`, `sexta`, `sabado`) VALUES (2, 2, 'Redação', 'Biologia', 'Matemática', 'Geografia', 'Português', 'Física', 'Simulados');
INSERT INTO `nextage`.`cronograma_estudos` (`id_cronograma`, `id_usuario`, `domingo`, `segunda`, `terca`, `quarta`, `quinta`, `sexta`, `sabado`) VALUES (3, 3, 'Química', 'História', 'Matemática', 'Português', 'Biologia', 'Redação', 'Descanso');

COMMIT;


-- -----------------------------------------------------
-- Data for table `nextage`.`cronometros`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`cronometros` (`id_cronometro`, `id_usuario`, `data`, `tempo_estudado`) VALUES (1, 1, '2025-05-10', '01:30:00');
INSERT INTO `nextage`.`cronometros` (`id_cronometro`, `id_usuario`, `data`, `tempo_estudado`) VALUES (2, 2, '2025-05-10', '02:00:00');
INSERT INTO `nextage`.`cronometros` (`id_cronometro`, `id_usuario`, `data`, `tempo_estudado`) VALUES (3, 3, '2025-05-10', '01:15:00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `nextage`.`vestibulares`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`vestibulares` (`id_vestibular`, `edicao`, `nome`, `banca`, `ano`) VALUES (1, 1, 'ENEM', 'INEP', 2023);
INSERT INTO `nextage`.`vestibulares` (`id_vestibular`, `edicao`, `nome`, `banca`, `ano`) VALUES (2, 1, 'FUVEST', 'FUVEST', 2024);
INSERT INTO `nextage`.`vestibulares` (`id_vestibular`, `edicao`, `nome`, `banca`, `ano`) VALUES (3, 1, 'UNICAMP', 'Comvest', 2025);

COMMIT;


-- -----------------------------------------------------
-- Data for table `nextage`.`questoes`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`questoes` (`id_questao`, `id_vestibular`, `id_alternativa_correta`, `explicacao`, `enunciado`, `imagem`) VALUES (1, 1, 2, '', 'A exposição a alguns níveis sonoros pode causar lesões auditivas. Por isso, em uma indústria, são adotadas medidas preventivas de acordo com a máquina que o funcionário opera e o nível N de intensidade do som, medido em decibel (dB), a que o operário é exposto, sendo  Imagem associada para resolução da questão I a intensidade do som e I0 = 10−12 W/m2.', NULL);
INSERT INTO `nextage`.`questoes` (`id_questao`, `id_vestibular`, `id_alternativa_correta`, `explicacao`, `enunciado`, `imagem`) VALUES (2, 2, 10, NULL, 'A arte foi e ainda pode ser utilizada para criar, reforçar e disseminar ideias, valores e estereótipos, mas também pode colocá-los em discussão. A obra “Sentem para jantar”, de Gê Viana, faz parte da série “Atualizações traumáticas de Debret”, na qual o artista propõe uma revisão iconográfica da história do Brasil tendo como referência as obras de JeanBaptiste Debret, especificamente aquelas presentes em “Viagem Pitoresca e Histórica ao Brasil” (1834-1839), publicação que pautou de maneira imagética o período colonial brasileiro. Em sua revisão, Gê Viana dá continuidade ao seu projeto de análise crítica de representações históricas, produzindo releituras de algumas dessas obras, dentre as quais, a obra “Um jantar brasileiro”, do artista francês. A seguir, são reproduzidos os quadros desses dois artistas. Com base nas informações e imagens apresentadas, assinale a alternativa que corresponde à abordagem adotada por Gê Viana em sua obra “Sentem para jantar”, ao utilizar como referência a obra “Um jantar brasileiro”, de Jean-Baptiste Debret.', NULL);
INSERT INTO `nextage`.`questoes` (`id_questao`, `id_vestibular`, `id_alternativa_correta`, `explicacao`, `enunciado`, `imagem`) VALUES (3, 3, 13, NULL, 'Em humanos, o sexo é determinado pela presença dos cromossomos sexuais X e Y, que são considerados parcialmente (i) _________. A inativação de um cromossomo X é um processo aleatório e foi demonstrado que os (ii) _________ no corpús culo de Barr são inativos, o que significa que eles não serão (iii) _________. A inativação do cromossomo X é um processo de controle epigenético, que molda o funcionamento do (iv) _________ sem alterá-lo, e iguala a atividade gênica das mulheres à dos homens.', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `nextage`.`questoes_conteudos`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`questoes_conteudos` (`id_questao`, `id_conteudo`) VALUES (1, 1);
INSERT INTO `nextage`.`questoes_conteudos` (`id_questao`, `id_conteudo`) VALUES (2, 2);
INSERT INTO `nextage`.`questoes_conteudos` (`id_questao`, `id_conteudo`) VALUES (3, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `nextage`.`relatorio_desempenho`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`relatorio_desempenho` (`id_relatorio`, `id_usuario`, `horas_estudadas`, `total_erros`, `total_acertos`) VALUES (1, 1, '02:30:00', 5, 20);
INSERT INTO `nextage`.`relatorio_desempenho` (`id_relatorio`, `id_usuario`, `horas_estudadas`, `total_erros`, `total_acertos`) VALUES (2, 2, '01:45:00', 3, 18);
INSERT INTO `nextage`.`relatorio_desempenho` (`id_relatorio`, `id_usuario`, `horas_estudadas`, `total_erros`, `total_acertos`) VALUES (3, 3, '03:00:00', 8, 25);

COMMIT;


-- -----------------------------------------------------
-- Data for table `nextage`.`responder`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`responder` (`id_usuario`, `id_questao`, `data`, `certo`) VALUES (1, 1, '2025-05-11', TRUE);
INSERT INTO `nextage`.`responder` (`id_usuario`, `id_questao`, `data`, `certo`) VALUES (2, 2, '2025-05-11', FALSE);
INSERT INTO `nextage`.`responder` (`id_usuario`, `id_questao`, `data`, `certo`) VALUES (3, 3, '2025-05-11', TRUE);

COMMIT;


-- -----------------------------------------------------
-- Data for table `nextage`.`alternativas`
-- -----------------------------------------------------
START TRANSACTION;
USE `nextage`;
INSERT INTO `nextage`.`alternativas` (`id_alternativas`, `questoes_id_questao`, `texto`) VALUES (1, 1, 'I');
INSERT INTO `nextage`.`alternativas` (`id_alternativas`, `questoes_id_questao`, `texto`) VALUES (2, 1, 'II');
INSERT INTO `nextage`.`alternativas` (`id_alternativas`, `questoes_id_questao`, `texto`) VALUES (3, 1, 'III');
INSERT INTO `nextage`.`alternativas` (`id_alternativas`, `questoes_id_questao`, `texto`) VALUES (4, 1, 'IV');
INSERT INTO `nextage`.`alternativas` (`id_alternativas`, `questoes_id_questao`, `texto`) VALUES (5, 1, 'V');
INSERT INTO `nextage`.`alternativas` (`id_alternativas`, `questoes_id_questao`, `texto`) VALUES (6, 2, 'Gê Viana reproduz, em sua obra, as mesmas relações sociais representadas na obra de Debret');
INSERT INTO `nextage`.`alternativas` (`id_alternativas`, `questoes_id_questao`, `texto`) VALUES (7, 2, 'Gê Viana exalta, em sua obra, especialmente as características físicas das pessoas retratadas, enquanto Debret enfatiza as relações pessoais.');
INSERT INTO `nextage`.`alternativas` (`id_alternativas`, `questoes_id_questao`, `texto`) VALUES (8, 2, 'Gê Viana emprega, em sua obra, as mesmas técnicas e os mesmos materiais utilizados na obra de Debret, o que lhes confere grande semelhança.');
INSERT INTO `nextage`.`alternativas` (`id_alternativas`, `questoes_id_questao`, `texto`) VALUES (9, 2, 'Gê Viana ignora aspectos relacionados a questões étnico-raciais em sua releitura da obra de Debret, focando apenas na estética visual da obra.');
INSERT INTO `nextage`.`alternativas` (`id_alternativas`, `questoes_id_questao`, `texto`) VALUES (10, 2, 'Gê Viana busca desconstruir, em sua obra, os estereótipos étnico-raciais presentes na obra original de Debret.');
INSERT INTO `nextage`.`alternativas` (`id_alternativas`, `questoes_id_questao`, `texto`) VALUES (11, 3, '(i) homólogos; (ii) alelos; (iii) traduzidos; (iv) código genético.');
INSERT INTO `nextage`.`alternativas` (`id_alternativas`, `questoes_id_questao`, `texto`) VALUES (12, 3, '(i) autossomos; (ii) genes; (iii) transcritos; (iv) código genético.');
INSERT INTO `nextage`.`alternativas` (`id_alternativas`, `questoes_id_questao`, `texto`) VALUES (13, 3, '(i) homólogos; (ii) genes; (iii) transcritos; (iv) genoma.');
INSERT INTO `nextage`.`alternativas` (`id_alternativas`, `questoes_id_questao`, `texto`) VALUES (14, 3, '(i) autossomos; (ii) alelos; (iii) traduzidos; (iv) genoma.');

COMMIT;

